/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `${'/(tabs)'}/about` | `/about`; params?: Router.UnknownInputParams; } | { pathname: `/components/TaskItem`; params?: Router.UnknownInputParams; } | { pathname: `/components/TaskList`; params?: Router.UnknownInputParams; } | { pathname: `/components/TaskInput`; params?: Router.UnknownInputParams; } | { pathname: `/types/Task`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownInputParams; } | { pathname: `/../components/TaskList`; params?: Router.UnknownInputParams; } | { pathname: `/../components/TaskInput`; params?: Router.UnknownInputParams; } | { pathname: `/../components/TaskItem`; params?: Router.UnknownInputParams; } | { pathname: `/../types/Task`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `${'/(tabs)'}/about` | `/about`; params?: Router.UnknownOutputParams; } | { pathname: `/components/TaskItem`; params?: Router.UnknownOutputParams; } | { pathname: `/components/TaskList`; params?: Router.UnknownOutputParams; } | { pathname: `/components/TaskInput`; params?: Router.UnknownOutputParams; } | { pathname: `/types/Task`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/TaskList`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/TaskInput`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/TaskItem`; params?: Router.UnknownOutputParams; } | { pathname: `/../types/Task`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `${'/(tabs)'}/about${`?${string}` | `#${string}` | ''}` | `/about${`?${string}` | `#${string}` | ''}` | `/components/TaskItem${`?${string}` | `#${string}` | ''}` | `/components/TaskList${`?${string}` | `#${string}` | ''}` | `/components/TaskInput${`?${string}` | `#${string}` | ''}` | `/types/Task${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/index${`?${string}` | `#${string}` | ''}` | `/index${`?${string}` | `#${string}` | ''}` | `/../components/TaskList${`?${string}` | `#${string}` | ''}` | `/../components/TaskInput${`?${string}` | `#${string}` | ''}` | `/../components/TaskItem${`?${string}` | `#${string}` | ''}` | `/../types/Task${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `${'/(tabs)'}/about` | `/about`; params?: Router.UnknownInputParams; } | { pathname: `/components/TaskItem`; params?: Router.UnknownInputParams; } | { pathname: `/components/TaskList`; params?: Router.UnknownInputParams; } | { pathname: `/components/TaskInput`; params?: Router.UnknownInputParams; } | { pathname: `/types/Task`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownInputParams; } | { pathname: `/../components/TaskList`; params?: Router.UnknownInputParams; } | { pathname: `/../components/TaskInput`; params?: Router.UnknownInputParams; } | { pathname: `/../components/TaskItem`; params?: Router.UnknownInputParams; } | { pathname: `/../types/Task`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
    }
  }
}
